#!/bin/sh

[ -z "$FNAME_PATTERN" ] && FNAME_PATTERN="*.[p,i]"
[ -z "$FIND_IN_DIR" ]   && FIND_IN_DIR="db"
[ -z "$MAX_DEPTH" ]     && MAX_DEPTH="5"

# Exclusion. scripts resides in db
[ "$FIND_IN_DIR" == "scripts" ] && FIND_IN_DIR="db/scripts"

if [ "$SUBDIR_LIST" == "*" ] || [ -z "$SUBDIR_LIST" ]; then
  SUBDIR_LIST="-"
fi

echo "Looking for: $SRCH_PATTERN"
echo "---"

IFS=$' '
for sdir in ${SUBDIR_LIST}
do
  if [ "$sdir" == "-" ]; then 
    sdir=''
  else
    sdir='/'${sdir}
  fi

  find "${GITDIR}/${FIND_IN_DIR}${sdir}" -type f -name "${FNAME_PATTERN}" \
 			 -maxdepth ${MAX_DEPTH} | 
 	while read line
 	do
		[[ ${FIND_IN_DIR} =~ db*|cui*	]] && \
			 desc=`grep -inH 'Description: ' ${line}` || desc=""

 	  [ -z "$desc" ] && desc=$line':1:'
 	  echo $desc | sed -r 's/^'"$UNIXPATH"'/'"$UNIXDOS"'/'
 	done		 
  
done

echo "---"
echo "Done."
